function(CMakePythonVenv_create_virtual_environment)
    cmake_parse_arguments(args "" "NAME" "" ${ARGN})
    if(NOT args_NAME)
        message(FATAL_ERROR "${CMAKE_CURRENT_FUNCTION} called without NAME parameter")
    endif()
    CMakePythonVenv_is_target_defined("${args_NAME}" env_exists)
    if(env_exists)
        message(FATAL_ERROR "Python virtual environment named \"${args_NAME}\" already exists")
    endif()
    set(env_dir "${CMAKE_BINARY_DIR}/${args_NAME}.dir")
    CMakePythonVenv_find_program(Python_EXECUTABLE python3 NO_CACHE REQUIRED)
    CMakePythonVenv_execute_process(
        COMMAND "${Python_EXECUTABLE}" -m venv "${env_dir}"
        RESULT_VARIABLE result
    )
    if(NOT "${result}" STREQUAL "0")
        message(FATAL_ERROR "could not create Python virtual environment")
    endif()
    CMakePythonVenv_add_custom_target("${args_NAME}")
    CMakePythonVenv_set_property(TARGET "${args_NAME}" PROPERTY ENV_DIR "${env_dir}")
endfunction()

function(CMakePythonVenv_install_packages)
    cmake_parse_arguments(args "" "NAME;REQUIREMENTS_FILE" "" ${ARGN})
    if(NOT args_NAME)
        message(FATAL_ERROR "${CMAKE_CURRENT_FUNCTION} called without NAME parameter")
    endif()
    CMakePythonVenv_is_target_defined("${args_NAME}" env_exists)
    if(NOT env_exists)
        message(FATAL_ERROR "Python virtual environment named \"${args_NAME}\" does not exist")
    endif()
    if(NOT args_REQUIREMENTS_FILE)
        message(FATAL_ERROR "${CMAKE_CURRENT_FUNCTION} called without packages to install")
    endif()
    if(args_REQUIREMENTS_FILE)
        cmake_path(ABSOLUTE_PATH args_REQUIREMENTS_FILE BASE_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}")
        CMakePythonVenv_get_property(Python_ROOT_DIR TARGET "${args_NAME}" PROPERTY ENV_DIR)
        CMakePythonVenv_find_package(Python)
        CMakePythonVenv_execute_process(
            COMMAND "${Python_EXECUTABLE}" -m pip install -r "${args_REQUIREMENTS_FILE}"
            RESULT_VARIABLE result
        )
        if(NOT "${result}" STREQUAL "0")
            message(FATAL_ERROR "could not install packages from ${args_REQUIREMENTS_FILE} file")
        endif()
    endif()
endfunction()